//Reference 1. https://msdn.microsoft.com/en-us/library/windows/desktop/aa363214(v=vs.85).aspx
//			2. https://msdn.microsoft.com/en-us/library/296az74e.aspx

#define BAUD_RATE CBR_9600
#define BYTE_SIZE 8
#define STOP_BITS ONESTOPBIT
#define PARITY NOPARITY
#define F_DTR_CONTROL DTR_CONTROL_ENABLE
#define SERIAL_QUEUE_SIZE_IN 4096
#define SERIAL_QUEUE_SIZE_OUT 4096
#define SERIAL_TIMEOUT_READ_INTERVAL_TIMEOUT ULONG_MAX
#define SERIAL_TIMEOUT_READ_TOTAL_TIMEOUT_MULTIPLIER 0
#define SERIAL_TIMEOUT_READ_TOTAL_TIMEOUT_CONSTANT 0
#define SERIAL_TIMEOUT_WRITE_TOTAL_TIMEOUT_MULTIPLIER 0
#define SERIAL_TIMEOUT_WRITE_TOTAL_TIMEOUT_CONSTANT 2000